# Generated by Django 3.1.5 on 2021-01-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210122_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='categorie',
            new_name='category',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
