# Generated by Django 3.1.5 on 2021-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210122_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
