# Generated by Django 3.1.5 on 2021-01-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210120_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Vehicle',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
