# Generated by Django 3.1.5 on 2021-01-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210120_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='created_date',
            new_name='launch_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='expire_date',
        ),
    ]
