# Generated by Django 3.1.5 on 2021-01-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210120_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='stock.vendor'),
        ),
    ]
