# Generated by Django 3.1.5 on 2021-01-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210120_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.vendor'),
        ),
    ]
